# Generated by Django 3.2.6 on 2021-08-08 11:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_personalprofile_options'),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to='members.personalprofile'),
        ),
    ]
