# Generated by Django 3.2.6 on 2021-08-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['reg_year', 'pass_year', 'reg_no', 'last_name', 'first_name', 'middle_name', 'birth_date'], 'verbose_name': 'Registered Student', 'verbose_name_plural': 'Registered Students'},
        ),
    ]
