# Generated by Django 3.2.5 on 2021-07-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('00_PT', 'Patron'), ('01_PR', 'President'), ('02_VP', 'Vice President'), ('03_SC', 'Secretary'), ('04_TR', 'Treasurer'), ('05_MB', 'Member')], max_length=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
            ],
            options={
                'verbose_name': 'Committee member',
                'verbose_name_plural': 'Committee members',
                'ordering': ['position', 'member__last_name'],
            },
        ),
    ]
