# Generated by Django 3.2.5 on 2021-07-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('clap_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('clap_count', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='album', verbose_name='Image')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.album')),
            ],
        ),
    ]
