# Generated by Django 3.2.6 on 2021-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='aws_file_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
