# Generated by Django 3.2.6 on 2021-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_personalprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('miss', 'Miss'), ('mrs', 'Mrs'), ('dr', 'Dr')], help_text='Title', max_length=10, null=True),
        ),
    ]
